name: 04. Build Main Wheels

on:
  workflow_dispatch:
    inputs:
      build_sdist:
        description: 'Whether to build source distribution'
        required: false
        type: boolean
        default: false
      os_json:
        description: 'JSON string of runner labels to build on (ubuntu-24.04=x86_64, ubuntu-24.04-arm=aarch64, macos-14=arm64, macos-15-intel=x86_64, windows-latest=x86_64)'
        required: false
        type: string
        default: '["ubuntu-24.04", "ubuntu-24.04-arm", "macos-14", "macos-15-intel", "windows-latest"]'
      python_json:
        description: 'JSON string of Python versions'
        required: false
        type: string
        default: '["3.10"]'

permissions:
  contents: read

jobs:
  build:
    name: Build wheels for main branch
    uses: ./.github/workflows/_build.yml
    with:
      os_json: ${{ inputs.os_json }}
      python_json: ${{ inputs.python_json }}
      build_sdist: ${{ inputs.build_sdist }}
      build_wheels: true
